name: Deploy QGS

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: build-cache
          key: buildx-${{ hashFiles('**/*') }}
          restore-keys: |
            buildx-

      - name: inject buildx-qgs into docker
        uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
        with:
          cache-map: |
            {
              "build-cache": {"target": "/tmp/.buildx-cache", "id": "1"}
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: sebbalex/quarkus-gs:latest
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
