name: Deploy QGS

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: /code/quarkus-gs/m2
          key: buildx-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            buildx-m2

      # - name: inject buildx-qgs into docker
      #   uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
      #   with:
      #     cache-map: |
      #       {
      #         "gha-mvn-cache": {"target": "/code/quarkus-gs/m2", "id": "1"}
      #       }
      #     skip-extraction: false #${{ steps.cache.outputs.cache-hit }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: sebbalex/quarkus-gs:latest
          file: Dockerfile
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          cache-from: type=local,src=/code/quarkus-gs/m2
          cache-to: type=local,dest=/code/quarkus-gs/m2-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /code/quarkus-gs/m2
          mv /code/quarkus-gs/m2-new /code/quarkus-gs/m2
