name: Deploy QGS

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Cache Docker layers
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        id: cache
        with:
          path: build-cacheee
          key: buildx-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            buildx-

      - name: inject buildx-qgs into docker
        # uses: reproducible-containers/buildkit-cache-dance@v2.1.4
        uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
        with:
          # cache-source: build-cacheee
          # cache-target: /tmp/.buildx-cacheee
          cache-map: |
            {
              "build-cacheee": "/tmp/.buildx-cacheee"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          push: false
          tags: sebbalex/quarkus-gs:latest
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

