name: Deploy QGS

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      # - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
      #   with:
      #     path: |
      #       ~/.m2/repository
      #       /root/.m2/repository
      #     key: cache-${{ hashFiles('**/pom.xml') }}

      # - name: Build, tag
      #   id: build-image
      #   working-directory: src/
      #   run: |
      #     docker build -f ./quarkus-gs/Dockerfile -t sebbalex/quarkus-gs:latest \
      #     docker push sebbalex/quarkus-gs:latest
      #     echo "image=sebbalex/quarkus-gs:latest" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: gha-mvn-cache
          key: buildx-${{ hashFiles('**/pom.xml') }}
          # restore-keys: |
          #   buildx-m2

      - name: inject buildx-qgs into docker
        uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
        with:
          cache-map: |
            {
              "gha-mvn-cache": "/code/quarkus-gs/m2"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: sebbalex/quarkus-gs:latest
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
